version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py test"
    container_name: spe3
    volumes:
      - .:/spe3
    ports:
      - "8000:8000"