# Generated by Django 2.0.13 on 2019-04-11 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='job_desc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.Job'),
        ),
    ]
