# Generated by Django 2.0.13 on 2019-04-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='address',
            new_name='street',
        ),
    ]
