# Generated by Django 2.0.13 on 2019-04-19 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobile_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only 0-9 are allowed.'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only 0-9 are allowed.'), django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
