# Generated by Django 2.0.13 on 2019-04-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20190403_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
