# Generated by Django 2.0.13 on 2019-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_auto_20190421_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
