# Generated by Django 2.0.13 on 2019-04-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_auto_20190421_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='out_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('i', 'IN'), ('o', 'OUT')], default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
