# Generated by Django 2.0.13 on 2019-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_auto_20190421_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
