# Generated by Django 2.2 on 2019-04-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_remove_salarystructure_gross_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='gross_salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
