# Generated by Django 2.2 on 2019-04-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_salarystructure_gross_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystructure',
            name='gross_salary',
        ),
    ]
