# Generated by Django 2.0.13 on 2019-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_auto_20190421_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
