# Generated by Django 2.0.13 on 2019-04-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_attendance_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='number',
        ),
    ]
