# Generated by Django 2.0.13 on 2019-04-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
