# Generated by Django 2.0.13 on 2019-04-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_salary_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='bonus',
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
