# Generated by Django 2.0.13 on 2019-04-21 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_auto_20190421_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=3),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateField(default=datetime.date(2019, 4, 21)),
        ),
    ]
