# Generated by Django 2.0.13 on 2019-04-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_auto_20190421_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
