# Generated by Django 2.0.13 on 2019-04-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_auto_20190424_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='leave',
            field=models.IntegerField(default=0),
        ),
    ]
